### ISSUE TITLE
Data not shown & customize.yaml

### ISSUE THREAD

**Issue by sainio** [joriws/nilan2homeassistant#1]
Hi,

there is no customize.yaml and no explanation what to put into it?

I can get the data to main dashboard but the NilanEX.svg tuned Dashboard shows unvailable for all values.

Have you managed to change Nilan register values with Home assistant yet?

**Comment by joriws** [comment]
Ok, there is a difference in Home assistant setups. On my HASS-based installation I had include for customize.yaml. But for this configuration it is not necessary, only the "packages" and "nilanec" -lines are, and they are under "homeassistant"-keyword:
```
homeassistant:
  customize: !include customize.yaml (<- this line can be omitted, if it is not by default on your home assistant installation)
  packages:
    nilanec: !include modbus_nilanec.yaml
```

I've initial own configuration for low and high ventilation modes, but it is not pushed to github yet. There are some issues and maybe setting automation like forced high ventilation stays on for max 2h then resets to normal operation.
